# Generated by Django 5.2.3 on 2025-07-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(unique=True)),
                ('image', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('time_ago', models.CharField(blank=True, max_length=50)),
                ('published_at', models.CharField(blank=True, max_length=100)),
                ('full_text', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, default='gazeta.uz', max_length=50)),
            ],
        ),
    ]
