# Generated by Django 5.2.3 on 2025-07-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_gazetanews_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazetanews',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gazetanews',
            name='link',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='gazetanews',
            name='time_ago',
            field=models.CharField(max_length=100),
        ),
    ]
