# Generated by Django 5.2.3 on 2025-07-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_gazetanews_image_alter_gazetanews_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gazetanews',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='gazetanews',
            name='image',
            field=models.URLField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
    ]
